package me.wcy.init.compiler

object ProcessorUtils {
    const val PARAM_NAME = "taskList"
    const val METHOD_NAME = "loadTask"
    const val PACKAGE_NAME = "me.wcy.init.apt.taskloader"
    const val JAVADOC = "DO NOT EDIT THIS FILE! IT WAS GENERATED BY INIT.\n"

    fun formatModuleName(moduleName: String): String {
        return moduleName.replace('-', '_')
    }
}